### ISSUE TITLE
Add support for bower & improve documentation

### ISSUE THREAD

**Issue by jvorcak** [pqx/react-ui-tree#1]
Hi,

This plugin looks exactly like something I was looking for. If it's available in Bower and has some documentation, it would be perfect! Thank you very much for this.

**Comment by wangzuo** [comment]
Do you use react with bower? will release a formal version soon.

**Comment by jvorcak** [comment]
We've started using Angular.JS for our project and we hit some performance issues. For some components we need to integrate React. This plugin would fulfill our needs as we need to do very complex DOM with a lot of functionality inside the tree.

**Comment by wangzuo** [comment]
Pretty cool, will try to make it more friendly to use.
