### ISSUE TITLE
leaf node support

### ISSUE THREAD

**Issue by luin** [pqx/react-ui-tree#13]
Are there any planing to support leaf node?

Particularly, I'm implementing a file manager, in which there are two types of nodes, folder and file. You can only drag a file or folder into a folder, but can't drag them into a file. It seems a little hard to achieve this behaviour using this lib.

**Comment by wangzuo** [comment]
Yes, this is a big problem. I will try to implement this feature.

**Comment by luin** [comment]
Cool! Looking forward to it :laughing:

**Comment by wangzuo** [comment]
I think `node.leaf` is supported now, you can check the updated example.

**Comment by luin** [comment]
Awesome!
