### ISSUE TITLE
Click on a node opens all siblings too

### ISSUE THREAD

**Issue by saelfaer** [pqx/react-ui-tree#5]
I noticed odd behaviour when testing the demo at the demo page.
when I close the tree, and click 1 of the nodes to open, it's siblings pop open as well.

**note** when I click the arrow it only opens the one, but when I click the name it opens all siblings.

see gif for detail info
![weird-behaviour](https://cloud.githubusercontent.com/assets/473305/9099309/fd3e2598-3bcf-11e5-8a3e-ff897a52480e.gif)

**Comment by wangzuo** [comment]
Thanks!
