### ISSUE TITLE
Explicitly tell people to name their import as "Tree"

### ISSUE THREAD

**Issue by KevinMongiello** [pqx/react-ui-tree#52]
Just tried to get the example working for hours, and realized that I had to 
`import Tree from 'react-ui-tree'`
Instead of: 
`import reactTree from 'react-ui-tree'`

**Comment by alexherns** [comment]
@KevinMongiello you can import as whatever you'd like but react requires you to use upper-case names for user-defined components: https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized

Everything should work if you `import ReactTree from 'react-ui-tree'` instead, but the component must be capitalized if you are going to try to render it

**Comment by KevinMongiello** [comment]
@alexherns hm, Interesting. I'm typically do follow that convention (without knowing the difference!).  Thanks for the explanation.
