### ISSUE TITLE
webpack: Failed to compile with npm start

### ISSUE THREAD

**Issue by fashman** [pqx/react-ui-tree#59]
when i run the demo ,it throw this error.
ERROR in ./example/app.js
Module build failed: SyntaxError: Unexpected token (12:8)
```
  10 |
  11 | class App extends Component {
> 12 |   state = {
     |         ^
  13 |     active: null,
  14 |     tree: tree
  15 |   };
```

**Comment by wangzuo** [comment]
Make sure you run `yarn` or `npm install` ahead

**Comment by fashman** [comment]
i add .babelrc file in root with:
```
{ 
  "presets": [ "react","es2015","stage-0"],
  "plugins": ["transform-class-properties"]
}
```
than it success;

**Comment by wangzuo** [comment]
`transform-class-properties` should be included in `stage-0`, very strange
