### ISSUE TITLE
Disable drag&drop

### ISSUE THREAD

**Issue by vomchik** [pqx/react-ui-tree#6]
How can I disabling drag&drop?

**Comment by wangzuo** [comment]
More details?

**Comment by vomchik** [comment]
How can i turn off this feature?

**Comment by wangzuo** [comment]
Oh, this component is for drag & drop tree editing, you may try other components like [react-treeview](https://www.npmjs.com/package/react-treeview).

**Comment by vomchik** [comment]
Ok. I will use another component.
27 авг. 2015 г. 3:48 пользователь "Wang Zuo" <notifications@github.com>
написал:

**Comment by Radivarig** [comment]
`e.stopPropagation()` from `onMouseDown` like this
```js
renderNode(node) {
    return (
      <span
        className={'node' +(node === this.state.active ? ' is-active' : '')}
        onClick={this.onClickNode.bind(null, node)}
        onMouseDown={node.undraggable ? function(e){e.stopPropagation()} : undefined}
      >
        {node.module}
      </span>
    )
  }
```

**Comment by wangzuo** [comment]
looks cool

**Comment by bonuanilkumar** [comment]
Thanks!!
